// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsvKAne5AqPda1gHdbPz8X0CEJbzEjRFo',
    appId: '1:43834130301:web:77ea3540f5559e6b5b1614',
    messagingSenderId: '43834130301',
    projectId: 'vetement-50d99',
    authDomain: 'vetement-50d99.firebaseapp.com',
    databaseURL: 'https://vetement-50d99-default-rtdb.firebaseio.com',
    storageBucket: 'vetement-50d99.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VZvE-2UmPj283YeUzp1CoPD7KVwtY_c',
    appId: '1:43834130301:android:15e22eef4ba191775b1614',
    messagingSenderId: '43834130301',
    projectId: 'vetement-50d99',
    databaseURL: 'https://vetement-50d99-default-rtdb.firebaseio.com',
    storageBucket: 'vetement-50d99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0ev6xOjIXRdj1MOIMdde3zSAO9wbHz8',
    appId: '1:43834130301:ios:f49ae5684ff38ded5b1614',
    messagingSenderId: '43834130301',
    projectId: 'vetement-50d99',
    databaseURL: 'https://vetement-50d99-default-rtdb.firebaseio.com',
    storageBucket: 'vetement-50d99.firebasestorage.app',
    iosBundleId: 'com.ines.inesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0ev6xOjIXRdj1MOIMdde3zSAO9wbHz8',
    appId: '1:43834130301:ios:f49ae5684ff38ded5b1614',
    messagingSenderId: '43834130301',
    projectId: 'vetement-50d99',
    databaseURL: 'https://vetement-50d99-default-rtdb.firebaseio.com',
    storageBucket: 'vetement-50d99.firebasestorage.app',
    iosBundleId: 'com.ines.inesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsvKAne5AqPda1gHdbPz8X0CEJbzEjRFo',
    appId: '1:43834130301:web:5e543790aac506f35b1614',
    messagingSenderId: '43834130301',
    projectId: 'vetement-50d99',
    authDomain: 'vetement-50d99.firebaseapp.com',
    databaseURL: 'https://vetement-50d99-default-rtdb.firebaseio.com',
    storageBucket: 'vetement-50d99.firebasestorage.app',
  );
}
